using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace OwnDay.Infrastructure.Persistence.Migrations;

[DbContext(typeof(OwnDayDbContext))]
[Migration("202609260002_AddStructuredItems")]
public partial class AddStructuredItems : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
            CREATE TABLE projects (
                id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT "PK_projects" PRIMARY KEY,
                user_id bigint NOT NULL,
                title character varying(200) NOT NULL,
                status integer NOT NULL,
                created_at timestamp with time zone NOT NULL,
                completed_at timestamp with time zone NULL,
                CONSTRAINT "AK_projects_id_user_id" UNIQUE (id, user_id),
                CONSTRAINT "CK_projects_status_completed_at" CHECK
                    ((status = 0 AND completed_at IS NULL) OR (status = 1 AND completed_at IS NOT NULL))
            );
            CREATE INDEX "IX_projects_user_id_status_created_at_id"
                ON projects (user_id, status, created_at, id);
            ALTER TABLE actions ADD COLUMN project_id bigint NULL;
            CREATE INDEX "IX_actions_project_id_user_id" ON actions (project_id, user_id);
            ALTER TABLE actions ADD CONSTRAINT "FK_actions_projects_project_id_user_id"
                FOREIGN KEY (project_id, user_id) REFERENCES projects (id, user_id);
            """);

        migrationBuilder.Sql("""
            CREATE TABLE someday_maybes (
                id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT "PK_someday_maybes" PRIMARY KEY,
                user_id bigint NOT NULL,
                text character varying(200) NOT NULL,
                status integer NOT NULL,
                created_at timestamp with time zone NOT NULL,
                archived_at timestamp with time zone NULL,
                project_id bigint NULL,
                CONSTRAINT "CK_someday_maybes_status_archived_at" CHECK
                    ((status = 0 AND archived_at IS NULL) OR (status = 1 AND archived_at IS NOT NULL)),
                CONSTRAINT "FK_someday_maybes_projects_project_id_user_id"
                    FOREIGN KEY (project_id, user_id) REFERENCES projects (id, user_id)
            );
            CREATE INDEX "IX_someday_maybes_user_id_status_created_at_id"
                ON someday_maybes (user_id, status, created_at, id);
            CREATE INDEX "IX_someday_maybes_project_id_user_id"
                ON someday_maybes (project_id, user_id);
            """);

        migrationBuilder.Sql("""
            CREATE TABLE "references" (
                id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT "PK_references" PRIMARY KEY,
                user_id bigint NOT NULL,
                text character varying(200) NOT NULL,
                status integer NOT NULL,
                created_at timestamp with time zone NOT NULL,
                archived_at timestamp with time zone NULL,
                project_id bigint NULL,
                CONSTRAINT "CK_references_status_archived_at" CHECK
                    ((status = 0 AND archived_at IS NULL) OR (status = 1 AND archived_at IS NOT NULL)),
                CONSTRAINT "FK_references_projects_project_id_user_id"
                    FOREIGN KEY (project_id, user_id) REFERENCES projects (id, user_id)
            );
            CREATE INDEX "IX_references_user_id_status_created_at_id"
                ON "references" (user_id, status, created_at, id);
            CREATE INDEX "IX_references_project_id_user_id"
                ON "references" (project_id, user_id);
            """);

        migrationBuilder.Sql("""
            CREATE TABLE waiting_fors (
                id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT "PK_waiting_fors" PRIMARY KEY,
                user_id bigint NOT NULL,
                description character varying(200) NOT NULL,
                source character varying(200) NULL,
                waiting_since timestamp with time zone NOT NULL,
                status integer NOT NULL,
                created_at timestamp with time zone NOT NULL,
                resolved_at timestamp with time zone NULL,
                project_id bigint NULL,
                CONSTRAINT "CK_waiting_fors_status_resolved_at" CHECK
                    ((status = 0 AND resolved_at IS NULL) OR (status = 1 AND resolved_at IS NOT NULL)),
                CONSTRAINT "FK_waiting_fors_projects_project_id_user_id"
                    FOREIGN KEY (project_id, user_id) REFERENCES projects (id, user_id)
            );
            CREATE INDEX "IX_waiting_fors_user_id_status_created_at_id"
                ON waiting_fors (user_id, status, created_at, id);
            CREATE INDEX "IX_waiting_fors_project_id_user_id"
                ON waiting_fors (project_id, user_id);
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
            DROP TABLE waiting_fors;
            DROP TABLE "references";
            DROP TABLE someday_maybes;
            ALTER TABLE actions DROP CONSTRAINT "FK_actions_projects_project_id_user_id";
            DROP INDEX "IX_actions_project_id_user_id";
            ALTER TABLE actions DROP COLUMN project_id;
            DROP TABLE projects;
            """);
    }
}
