using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace OwnDay.Infrastructure.Persistence.Migrations;

[DbContext(typeof(OwnDayDbContext))]
[Migration("202609270001_AddInboxItems")]
public partial class AddInboxItems : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
            CREATE TABLE inbox_items (
                id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT "PK_inbox_items" PRIMARY KEY,
                user_id bigint NOT NULL,
                original_text text NOT NULL,
                captured_at timestamp with time zone NOT NULL,
                status integer NOT NULL,
                processed_at timestamp with time zone NULL,
                discarded_at timestamp with time zone NULL,
                target_kind integer NULL,
                target_id bigint NULL,
                CONSTRAINT "CK_inbox_items_user_id" CHECK (user_id > 0),
                CONSTRAINT "CK_inbox_items_original_text" CHECK (original_text ~ '[^[:space:]]'),
                CONSTRAINT "CK_inbox_items_lifecycle" CHECK (
                    (status = 0 AND processed_at IS NULL AND discarded_at IS NULL AND target_kind IS NULL AND target_id IS NULL) OR
                    (status = 1 AND processed_at IS NOT NULL AND discarded_at IS NULL AND target_kind IS NOT NULL AND target_kind BETWEEN 0 AND 4 AND target_id IS NOT NULL AND target_id > 0 AND processed_at >= captured_at) OR
                    (status = 2 AND processed_at IS NULL AND discarded_at IS NOT NULL AND target_kind IS NULL AND target_id IS NULL AND discarded_at >= captured_at))
            );
            CREATE INDEX "IX_inbox_items_user_id_status_captured_at_id"
                ON inbox_items (user_id, status, captured_at, id);
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("DROP TABLE inbox_items;");
    }
}
